import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Layout & Navigation
    endSession: "End Session",
    highContrast: "High Contrast",
    fontSize: "Aa",
    language: "English",
    home: "Home",
    back: "Back",
    nagrikEye: "NagrikEye",
    selfServiceKiosk: "Self-Service Kiosk",
    contrast: "Contrast",
    
    // Home Dashboard
    selectService: "Select Service",
    electricity: "Electricity",
    gasUtility: "Gas Utility",
    municipal: "Municipal",
    comingSoon: "Coming Soon",

    // Gas Dashboard
    gasServices: "Gas Utility Services",
    payBill: "Pay Gas Bill",
    payBillDesc: "View and pay your outstanding gas bills",
    newConnection: "New Connection",
    newConnectionDesc: "Apply for a new piped gas connection",
    bookRefill: "Book Cylinder",
    bookRefillDesc: "Book your LPG cylinder refill online",
    registerComplaint: "Register Complaint",
    registerComplaintDesc: "Report issues with service or billing",
    trackStatus: "Track Status",
    trackStatusDesc: "Check status of applications/complaints",
    emergency: "Report Gas Leak",
    emergencyDesc: "24/7 emergency response service",

    // Buttons
    submit: "Submit",
    proceed: "Proceed",
    cancel: "Cancel",
    confirm: "Confirm",
    returnMenu: "Return to Menu",

    // Generic form labels
    consumerId: "Consumer ID",
    mobileNumber: "Mobile Number",
    enterDetails: "Enter Details",
    fetchingDetails: "Fetching Details...",
    fullName: "Full Name",
    emailAddr: "Email Address",
    aadhaarNumber: "Aadhaar Number",
    address: "Address",
    city: "City",
    pinCode: "PIN Code",
    uploadKyc: "Upload KYC Document",
    uploadPlaceholder: "Tap to capture or upload ID",
    trackingId: "Tracking ID",
    applicationId: "Application ID",
    complaintCategory: "Complaint Category",
    describeIssue: "Describe the Issue",
    submitComplaint: "Submit Complaint",
    selectRefillDate: "Select Refill Date",
    emergencyReport: "EMERGENCY REPORT",
    gasLeakage: "Gas Leakage",
    fireHazard: "Fire Hazard",
    pipelineDamage: "Pipeline Damage / Blast",
    reportNow: "REPORT NOW",
    billSummary: "Bill Summary",
    consumerName: "Consumer Name",
    dueDate: "Due Date",
    totalPayable: "Total Payable",
    pay: "Pay",
    paymentSuccess: "Payment Successful!",
    txnId: "Transaction ID",
    dateTime: "Date & Time",
    amountPaid: "Amount Paid",
    clickToProceed: "Click to Proceed",
    consumerInfo: "Consumer Info",
    refillAddress: "Refill Address",
    lastRefill: "Last Refill",
    status: "Status",
    enterTrackingId: "Enter Tracking ID/Complaint ID",
    checkStatus: "Check Status",
    issueType: "Issue Type",
    location: "Location",
    description: "Description",
    date: "Date",
    callFireDept: "1. Call Fire Department (101)",
    evacuateArea: "2. Evacuate the area immediately",
    doNotUseSwitches: "3. Do NOT use electrical switches",
    safetyInstructions: "Safety Instructions:",
    emergencyHotlines: "Emergency Hotlines",
    nationalEmergency: "National Emergency",
    gasEmergency: "Gas Emergency",
    fireDepartment: "Fire Department",
    nextStep: "Next Step",
    confirmAndSubmit: "Confirm & Submit Application",
    submitting: "Submitting...",
    enterDetailsId: "Please enter details exactly as per your official ID.",
    selectIdProof: "Select ID Proof Type",
    scannerProcessing: "Scanner processing ID...",
    docScanned: "Document Successfully Scanned",
    uploadPlaceholderDoc: "Place document on scanner bed and tap here",
    connPreference: "Connection Preference",
    lpgCylinder: "LPG Cylinder",
    pngGas: "PNG (Piped Gas)",
    reviewInfo: "Review Information",
    serviceType: "Service Type",
    appSubmitted: "Application Submitted!",
    requestUnderReview: "Your request is now under review by our department.",
    appTrackingId: "Application Tracking ID",
    noteDownId: "Please note down this ID or take a picture of the screen to track your application status later.",
    enterMobile: "Enter 10-digit Mobile",
    fetchBill: "Fetch Bill",
    processingPayment: "Processing Payment...",
    accountCredited: "Your account has been credited.",
    fetchingHistory: "Fetching History...",
    fetchBookingHistory: "Fetch Booking History",
    nextEligible: "Next Eligible Date",
    confirmBooking: "Confirm Refill Booking",
    processingBooking: "Processing Booking...",
    bookingConfirmed: "Booking Confirmed!",
    refillScheduled: "Your refill has been scheduled successfully.",
    expectedDelivery: "Expected Delivery by",
    supplyDelay: "Supply Delay",
    connectionIssue: "Connection Issue",
    billingIssue: "Billing Issue",
    briefDesc: "Brief description of the problem...",
    attachImage: "Attach Image / Video (Optional)",
    complaintRegistered: "Complaint Registered!",
    teamAssist: "Our team will assist you shortly.",
    noteDownTrackingId: "Please note down the tracking ID or take a picture of this screen.",
    enterRefNumber: "Enter the reference number provided during registration.",
    searchingSystem: "Searching System...",
    expectedResolution: "Expected Resolution",
    assignedTo: "Assigned To",
    trackAnotherId: "Track Another ID",
    transmittingAlert: "Transmitting Alert...",
    alertWarning: "Pressing this will instantly alert the nearest response team",
    tollFreeHelpline: "Toll-Free Helpline",
    kioskLocation: "Kiosk Location",
    autoSentResponders: "Auto-Sent to Responders",
    emergencyAlertSent: "Emergency Alert Sent!",
    rapidResponseDispatch: "A rapid response unit has been dispatched to your location.",
    leaveDoorsOpen: "Leave doors and windows open.",
    understoodReturn: "I Understand - Return to Menu",
    personalDetails: "Personal Details",
    installationAddress: "Installation Address",
    identityVerification: "Identity Verification (KYC)",
    aadhaarRec: "Aadhaar Card (Recommended)",
    voterId: "Voter ID",
    passport: "Passport",
    standardDelivery: "Standard cylinder delivery",
    directPipeline: "Direct pipeline to kitchen",
    step: "Step",
    of: "of",
  },
  hi: {
    // Layout & Navigation
    endSession: "सत्र समाप्त करें",
    highContrast: "उच्च कंट्रास्ट",
    fontSize: "Aa",
    language: "हिंदी",
    home: "होम",
    back: "वापस",
    nagrikEye: "नागरिक आई",
    selfServiceKiosk: "स्वयं सेवा कियोस्क",
    contrast: "कंट्रास्ट",
    
    // Home Dashboard
    selectService: "सेवा चुनें",
    electricity: "बिजली",
    gasUtility: "गैस उपयोगिता",
    municipal: "नगरपालिका",
    comingSoon: "जल्द आ रहा है",

    // Gas Dashboard
    gasServices: "गैस उपयोगिता सेवाएं",
    payBill: "गैस बिल का भुगतान करें",
    payBillDesc: "अपने बकाया गैस बिल देखें और भुगतान करें",
    newConnection: "नया कनेक्शन",
    newConnectionDesc: "पाइप गैस कनेक्शन के लिए आवेदन करें",
    bookRefill: "सिलेंडर बुक करें",
    bookRefillDesc: "अपना एलपीजी सिलेंडर रिफिल ऑनलाइन बुक करें",
    registerComplaint: "शिकायत दर्ज करें",
    registerComplaintDesc: "सेवा या बिलिंग से संबंधित समस्याओं की रिपोर्ट करें",
    trackStatus: "स्थिति ट्रैक करें",
    trackStatusDesc: "आवेदनों/शिकायतों की स्थिति जांचें",
    emergency: "गैस रिसाव की रिपोर्ट करें",
    emergencyDesc: "24/7 आपातकालीन प्रतिक्रिया सेवा",

    // Buttons
    submit: "जमा करें",
    proceed: "आगे बढ़ें",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    returnMenu: "मेनू पर वापस लौटें",

    // Generic form labels
    consumerId: "उपभोक्ता आईडी",
    mobileNumber: "मोबाइल नंबर",
    enterDetails: "विवरण दर्ज करें",
    fetchingDetails: "विवरण प्राप्त किया जा रहा है...",
    fullName: "पूरा नाम",
    emailAddr: "ईमेल पता",
    aadhaarNumber: "आधार कार्ड संख्या",
    address: "पता",
    city: "शहर",
    pinCode: "पिन कोड",
    uploadKyc: "केवाईसी दस्तावेज़ अपलोड करें",
    uploadPlaceholder: "आईडी कैप्चर या अपलोड करने के लिए टैप करें",
    trackingId: "ट्रैकिंग आईडी",
    applicationId: "आवेदन आईडी",
    complaintCategory: "शिकायत श्रेणी",
    describeIssue: "समस्या का वर्णन करें",
    submitComplaint: "शिकायत दर्ज करें",
    selectRefillDate: "रिफिल तिथि चुनें",
    emergencyReport: "आपातकालीन रिपोर्ट",
    gasLeakage: "गैस रिसाव",
    fireHazard: "आग का खतरा",
    pipelineDamage: "पाइपलाइन क्षति / विस्फोट",
    reportNow: "अभी रिपोर्ट करें",
    billSummary: "बिल सारांश",
    consumerName: "उपभोक्ता का नाम",
    dueDate: "देय तिथि",
    totalPayable: "कुल देय",
    pay: "भुगतान करें",
    paymentSuccess: "भुगतान सफल!",
    txnId: "लेनदेन आईडी",
    dateTime: "दिनांक और समय",
    amountPaid: "भुगतान की गई राशि",
    clickToProceed: "आगे बढ़ने के लिए क्लिक करें",
    consumerInfo: "उपभोक्ता जानकारी",
    refillAddress: "रिफिल पता",
    lastRefill: "अंतिम रिफिल",
    status: "स्थिति",
    enterTrackingId: "ट्रैकिंग आईडी/शिकायत आईडी दर्ज करें",
    checkStatus: "स्थिति जांचें",
    issueType: "समस्या का प्रकार",
    location: "स्थान",
    description: "विवरण",
    date: "दिनांक",
    callFireDept: "1. फायर विभाग को कॉल करें (101)",
    evacuateArea: "2. क्षेत्र को तुरंत खाली करें",
    doNotUseSwitches: "3. बिजली के स्विच का उपयोग न करें",
    safetyInstructions: "सुरक्षा निर्देश:",
    emergencyHotlines: "आपातकालीन हॉटलाइन",
    nationalEmergency: "राष्ट्रीय आपातकाल",
    gasEmergency: "गैस आपातकाल",
    fireDepartment: "अग्निशमन विभाग",
    nextStep: "अगला कदम",
    confirmAndSubmit: "पुष्टि करें और आवेदन जमा करें",
    submitting: "जमा किया जा रहा है...",
    enterDetailsId: "कृपया अपनी आधिकारिक आईडी के अनुसार विवरण दर्ज करें।",
    selectIdProof: "आईडी प्रमाण प्रकार चुनें",
    scannerProcessing: "स्कैनर आईडी प्रोसेस कर रहा है...",
    docScanned: "दस्तावेज़ सफलतापूर्वक स्कैन हो गया",
    uploadPlaceholderDoc: "स्कैनर बेड पर दस्तावेज़ रखें और यहां टैप करें",
    connPreference: "कनेक्शन प्राथमिकता",
    lpgCylinder: "एलपीजी सिलेंडर",
    pngGas: "पीएनजी (पाइप गैस)",
    reviewInfo: "जानकारी की समीक्षा करें",
    serviceType: "सेवा का प्रकार",
    appSubmitted: "आवेदन जमा किया गया!",
    requestUnderReview: "आपका अनुरोध अब हमारे विभाग द्वारा समीक्षाधीन है।",
    appTrackingId: "आवेदन ट्रैकिंग आईडी",
    noteDownId: "बाद में अपने आवेदन की स्थिति को ट्रैक करने के लिए कृपया इस आईडी को नोट कर लें या स्क्रीन की एक तस्वीर ले लें।",
    enterMobile: "10-अंकीय मोबाइल दर्ज करें",
    fetchBill: "बिल प्राप्त करें",
    processingPayment: "भुगतान संसाधित किया जा रहा है...",
    accountCredited: "आपके खाते में क्रेडिट कर दिया गया है।",
    fetchingHistory: "इतिहास प्राप्त किया जा रहा है...",
    fetchBookingHistory: "बुकिंग इतिहास प्राप्त करें",
    nextEligible: "अगली पात्र तिथि",
    confirmBooking: "रिफिल बुकिंग की पुष्टि करें",
    processingBooking: "बुकिंग संसाधित की जा रही है...",
    bookingConfirmed: "बुकिंग की पुष्टि हो गई!",
    refillScheduled: "आपकी रिफिल सफलतापूर्वक निर्धारित कर दी गई है।",
    expectedDelivery: "अपेक्षित डिलीवरी",
    supplyDelay: "आपूर्ति में देरी",
    connectionIssue: "कनेक्शन समस्या",
    billingIssue: "बिलिंग समस्या",
    briefDesc: "समस्या का संक्षिप्त विवरण...",
    attachImage: "छवि / वीडियो संलग्न करें (वैकल्पिक)",
    complaintRegistered: "शिकायत दर्ज की गई!",
    teamAssist: "हमारी टीम जल्द ही आपकी सहायता करेगी।",
    noteDownTrackingId: "कृपया ट्रैकिंग आईडी नोट कर लें या इस स्क्रीन की एक तस्वीर ले लें।",
    enterRefNumber: "पंजीकरण के दौरान प्रदान की गई संदर्भ संख्या दर्ज करें।",
    searchingSystem: "सिस्टम खोजा जा रहा है...",
    expectedResolution: "अपेक्षित समाधान",
    assignedTo: "को सौंपा गया",
    trackAnotherId: "एक और आईडी ट्रैक करें",
    transmittingAlert: "अलर्ट भेजा जा रहा है...",
    alertWarning: "इसे दबाने से निकटतम प्रतिक्रिया टीम को तुरंत अलर्ट मिल जाएगा",
    tollFreeHelpline: "टोल-फ्री हेल्पलाइन",
    kioskLocation: "कियोस्क स्थान",
    autoSentResponders: "प्रतिक्रियाकर्ताओं को स्वतः भेजा गया",
    emergencyAlertSent: "आपातकालीन अलर्ट भेजा गया!",
    rapidResponseDispatch: "एक त्वरित प्रतिक्रिया इकाई आपके स्थान पर भेज दी गई है।",
    leaveDoorsOpen: "दरवाजे और खिड़कियां खुले रखें।",
    understoodReturn: "मैं समझ गया - मेनू पर लौटें",
    personalDetails: "व्यक्तिगत विवरण",
    installationAddress: "स्थापना का पता",
    identityVerification: "पहचान सत्यापन (KYC)",
    aadhaarRec: "आधार कार्ड (अनुशंसित)",
    voterId: "वोटर आईडी",
    passport: "पासपोर्ट",
    standardDelivery: "मानक सिलेंडर डिलीवरी",
    directPipeline: "रसोई तक सीधी पाइपलाइन",
    step: "चरण",
    of: "का",
  }
};

const LanguageContext = createContext();

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'en' ? 'hi' : 'en'));
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
